"""add trial reminder sent at to tenants

Revision ID: 0a2744b82798
Revises: d04dd60cc8b2
Create Date: 2026-09-20 06:03:58.910194
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0a2744b82798'
down_revision: Union[str, None] = 'd04dd60cc8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('trial_reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'trial_reminder_sent_at')
    # ### end Alembic commands ###
