"""add_totp_revoked_tokens_groups_profile_versions

Revision ID: 45e601c124b1
Revises: e5ea7a3aa8d3
Create Date: 2026-04-20 13:22:59.370915
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '45e601c124b1'
down_revision: Union[str, None] = 'e5ea7a3aa8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
