"""add admin access requests

Revision ID: 88186ad468a3
Revises: 2b11b1b910db
Create Date: 2026-04-01 10:20:39.645740
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '88186ad468a3'
down_revision: Union[str, None] = '2b11b1b910db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
