"""initial schema

Revision ID: 8c183e249773
Revises: 
Create Date: 2026-03-28 08:35:26.983428
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8c183e249773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
