"""add password reset tokens

Revision ID: d04dd60cc8b2
Revises: f24fa616958b
Create Date: 2026-09-20 05:55:57.165034
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd04dd60cc8b2'
down_revision: Union[str, None] = 'f24fa616958b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
