"""add_software_packages

Revision ID: e5ea7a3aa8d3
Revises: fefc66193480
Create Date: 2026-04-02 09:40:12.671754
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e5ea7a3aa8d3'
down_revision: Union[str, None] = 'fefc66193480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
