"""add_billing_fields_to_tenants

Revision ID: f24fa616958b
Revises: 45e601c124b1
Create Date: 2026-04-20 17:25:09.202316
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f24fa616958b'
down_revision: Union[str, None] = '45e601c124b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('billing_status', sa.String(length=50), nullable=False, server_default='trialing'))
    op.add_column('tenants', sa.Column('plan_device_limit', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('tenants', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'plan_device_limit')
    op.drop_column('tenants', 'billing_status')
    # ### end Alembic commands ###
