"""add_software_requests

Revision ID: fefc66193480
Revises: 186b228acd97
Create Date: 2026-04-01 15:58:01.657951
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fefc66193480'
down_revision: Union[str, None] = '186b228acd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
